name: Jobs workflow
on:
    workflow_run:
        workflows: [First Workflow]
        types: 
            - completed
            
jobs:
    exist-html:
        runs-on: ubuntu-latest
        steps:
            - name: get repo code
              uses : actions/checkout@v7

            - name: validate html file
              run: test -f index.html
              
    exist-js:
        runs-on: ubuntu-latest
        steps:
            - name: get repo code
              uses : actions/checkout@v7

            - name: validate js file
              run: test -f script.js

    Validate-code:
        needs: [exist-html,exist-js]
        runs-on: ubuntu-latest
        steps:
            - name: get repo code
              uses : actions/checkout@v7

            - name: validate js file
              run: test -f script.js

            - name: validate html file
              run: npx htmlhint index.html
              