name: Second Workflow
on: workflow_dispatch

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: "welcome"
        run: echo "welcome to the second workflow"

  bye-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: "bye"
        run: echo "bye to the second workflow"
  